blank_issues_enabled: false
contact_links:
  - name: â“ Q&A
    url: https://github.com/epezent/implot/discussions/categories/q-a
    about: Have any questions or need help? Ask here!
  - name: ğŸ“¸ Gallery
    url: https://github.com/epezent/implot/discussions/180
    about: Share screenshots/videos of your projects using ImPlot!
